participants:
  - cl_type: lighthouse
    el_type: geth
  - cl_type: teku
    el_type: nethermind
  - cl_type: prysm
    el_type: reth
  - cl_type: lodestar
    el_type: besu
  - cl_type: nimbus
    el_type: erigon
  - cl_type: grandine
    el_type: ethrex
additional_services:
  - dora
